name: uniconnect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  dash_chat_2: ^0.0.20
  chat_gpt_sdk: ^3.0.7
  http: ^1.2.1
  provider: ^6.1.2
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.0.2
  intl: ^0.19.0
  chat_bubbles: ^1.5.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.0.11
  pdf: ^3.3.0
  line_icons: ^2.0.3
  material_symbols_icons: ^4.2758.0
  simple_icons: ^10.1.3
  webview_flutter: ^4.4.2
  webviewx_plus: ^0.5.0
  webview_flutter_web: ^0.2.2+4
  permission_handler: ^11.3.1
  dio: ^5.4.3+1
  sqflite: ^2.2.8+4
  toast: 0.3.0
  url_launcher: ^6.0.2
  fluttertoast: ^8.2.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  get_storage: ^2.1.1
  crypto: ^3.0.3
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  icons_launcher: ^2.1.7
  flutter_svg: ^2.0.10+1
  flutter_image_compress: ^2.3.0
  firebase_messaging: ^15.0.2
  firebase_in_app_messaging: ^0.8.0+2
  file_picker: ^8.0.6
  html: ^0.15.0
  qr_flutter: ^4.1.0




  cloud_firestore_platform_interface: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true



  assets:
    - assets/images/
    - assets/pdf/
    - assets/Data/
    - assets/svgs/
    - assets/svgs/event.svg
    - assets/pdf/sexual_harassment_policy.pdf
    - .env